name = "korean-food-learn"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "korean-food-db"
database_id = "45bff69e-e21f-4a97-9a0a-f573ac9a6780"

[vars]
ENVIRONMENT = "production"
